version: "3.1"
services:
  ldap:
    image: osixia/openldap
  enviroments:
    LDAP_DOMAIN: ldap.infrastruct.ru
    LDAP_ADMIN_PASSWORD: qwerty
  volumes:
    - ./ldap/data/slapd/database:/var/lib/ldap
    - ./ldap/data/slapd/config:/etc/ldap/slapd.d
    
    
  